// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package boojum_protocol_leader_election

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AggregationProposal struct {
	Type                 string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Deadline             *Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AggregationProposal) Reset()         { *m = AggregationProposal{} }
func (m *AggregationProposal) String() string { return proto.CompactTextString(m) }
func (*AggregationProposal) ProtoMessage()    {}
func (*AggregationProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *AggregationProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationProposal.Unmarshal(m, b)
}
func (m *AggregationProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationProposal.Marshal(b, m, deterministic)
}
func (m *AggregationProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationProposal.Merge(m, src)
}
func (m *AggregationProposal) XXX_Size() int {
	return xxx_messageInfo_AggregationProposal.Size(m)
}
func (m *AggregationProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationProposal.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationProposal proto.InternalMessageInfo

func (m *AggregationProposal) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AggregationProposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AggregationProposal) GetDeadline() *Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

type Timestamp struct {
	Sec                  int64    `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Nsec                 int64    `protobuf:"varint,2,opt,name=nsec,proto3" json:"nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSec() int64 {
	if m != nil {
		return m.Sec
	}
	return 0
}

func (m *Timestamp) GetNsec() int64 {
	if m != nil {
		return m.Nsec
	}
	return 0
}

type AggregationJob struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SubTrees             [][]byte `protobuf:"bytes,2,rep,name=subTrees,proto3" json:"subTrees,omitempty"`
	Label                int64    `protobuf:"varint,3,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationJob) Reset()         { *m = AggregationJob{} }
func (m *AggregationJob) String() string { return proto.CompactTextString(m) }
func (*AggregationJob) ProtoMessage()    {}
func (*AggregationJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *AggregationJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationJob.Unmarshal(m, b)
}
func (m *AggregationJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationJob.Marshal(b, m, deterministic)
}
func (m *AggregationJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationJob.Merge(m, src)
}
func (m *AggregationJob) XXX_Size() int {
	return xxx_messageInfo_AggregationJob.Size(m)
}
func (m *AggregationJob) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationJob.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationJob proto.InternalMessageInfo

func (m *AggregationJob) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AggregationJob) GetSubTrees() [][]byte {
	if m != nil {
		return m.SubTrees
	}
	return nil
}

func (m *AggregationJob) GetLabel() int64 {
	if m != nil {
		return m.Label
	}
	return 0
}

type AggregationResult struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Label                int64    `protobuf:"varint,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationResult) Reset()         { *m = AggregationResult{} }
func (m *AggregationResult) String() string { return proto.CompactTextString(m) }
func (*AggregationResult) ProtoMessage()    {}
func (*AggregationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *AggregationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationResult.Unmarshal(m, b)
}
func (m *AggregationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationResult.Marshal(b, m, deterministic)
}
func (m *AggregationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationResult.Merge(m, src)
}
func (m *AggregationResult) XXX_Size() int {
	return xxx_messageInfo_AggregationResult.Size(m)
}
func (m *AggregationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationResult.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationResult proto.InternalMessageInfo

func (m *AggregationResult) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AggregationResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AggregationResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AggregationResult) GetLabel() int64 {
	if m != nil {
		return m.Label
	}
	return 0
}

func init() {
	proto.RegisterType((*AggregationProposal)(nil), "boojum.protocol.leader_election.AggregationProposal")
	proto.RegisterType((*Timestamp)(nil), "boojum.protocol.leader_election.Timestamp")
	proto.RegisterType((*AggregationJob)(nil), "boojum.protocol.leader_election.AggregationJob")
	proto.RegisterType((*AggregationResult)(nil), "boojum.protocol.leader_election.AggregationResult")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x69, 0xb2, 0x2e, 0xbb, 0xcf, 0x65, 0xd1, 0x28, 0x52, 0xbc, 0x58, 0x7a, 0x2a, 0x1e,
	0x0a, 0xea, 0x2f, 0xf0, 0xe2, 0xc1, 0x93, 0x84, 0xc5, 0xab, 0x24, 0xcd, 0xa3, 0x44, 0xd2, 0xa6,
	0x24, 0xe9, 0xc1, 0xa3, 0xff, 0x5c, 0xfa, 0x56, 0x6a, 0x0f, 0x82, 0xde, 0xe6, 0x1b, 0x92, 0x37,
	0xc3, 0xc0, 0xbe, 0xc3, 0x18, 0x55, 0x8b, 0xb1, 0x1e, 0x82, 0x4f, 0x5e, 0xdc, 0x68, 0xef, 0xdf,
	0xc7, 0xee, 0x48, 0x8d, 0x77, 0xb5, 0x43, 0x65, 0x30, 0xbc, 0xa1, 0xc3, 0x26, 0x59, 0xdf, 0x97,
	0x9f, 0x19, 0x5c, 0x3c, 0xb6, 0x6d, 0xc0, 0x56, 0x4d, 0xfc, 0x12, 0xfc, 0xe0, 0xa3, 0x72, 0x42,
	0xc0, 0x2a, 0x7d, 0x0c, 0x98, 0x67, 0x45, 0x56, 0x6d, 0x25, 0x69, 0xb1, 0x07, 0x66, 0x4d, 0xce,
	0xc8, 0x61, 0xd6, 0x88, 0x27, 0xd8, 0x18, 0x54, 0xc6, 0xd9, 0x1e, 0x73, 0x5e, 0x64, 0xd5, 0xe9,
	0xfd, 0x6d, 0xfd, 0x47, 0x5e, 0x7d, 0xb0, 0x1d, 0xc6, 0xa4, 0xba, 0x41, 0xce, 0x7f, 0xcb, 0x3b,
	0xd8, 0xce, 0xb6, 0x38, 0x03, 0x1e, 0xb1, 0xa1, 0x5c, 0x2e, 0x27, 0x39, 0x55, 0xe9, 0x27, 0x8b,
	0x91, 0x45, 0xba, 0x7c, 0x85, 0xfd, 0xa2, 0xf5, 0xb3, 0xd7, 0xbf, 0x16, 0xbe, 0x86, 0x4d, 0x1c,
	0xf5, 0x21, 0x20, 0xc6, 0x9c, 0x15, 0xbc, 0xda, 0xc9, 0x99, 0xc5, 0x25, 0x9c, 0x38, 0xa5, 0xd1,
	0x51, 0x73, 0x2e, 0x8f, 0x50, 0x22, 0x9c, 0x2f, 0xee, 0x4a, 0x8c, 0xa3, 0x4b, 0xff, 0xda, 0xe2,
	0x0a, 0xd6, 0x81, 0x5e, 0xd3, 0xbd, 0x9d, 0xfc, 0xa6, 0x9f, 0x98, 0xd5, 0x22, 0x46, 0xaf, 0x69,
	0x9f, 0x87, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xfa, 0xc2, 0x10, 0xaf, 0x01, 0x00, 0x00,
}
