// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package boojum_protocol_leader_election

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AggregationProposal struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationProposal) Reset()         { *m = AggregationProposal{} }
func (m *AggregationProposal) String() string { return proto.CompactTextString(m) }
func (*AggregationProposal) ProtoMessage()    {}
func (*AggregationProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *AggregationProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationProposal.Unmarshal(m, b)
}
func (m *AggregationProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationProposal.Marshal(b, m, deterministic)
}
func (m *AggregationProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationProposal.Merge(m, src)
}
func (m *AggregationProposal) XXX_Size() int {
	return xxx_messageInfo_AggregationProposal.Size(m)
}
func (m *AggregationProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationProposal.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationProposal proto.InternalMessageInfo

func (m *AggregationProposal) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AggregationProposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AggregationRequest struct {
	SubTrees             [][]byte `protobuf:"bytes,1,rep,name=subTrees,proto3" json:"subTrees,omitempty"`
	Token                int64    `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationRequest) Reset()         { *m = AggregationRequest{} }
func (m *AggregationRequest) String() string { return proto.CompactTextString(m) }
func (*AggregationRequest) ProtoMessage()    {}
func (*AggregationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *AggregationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationRequest.Unmarshal(m, b)
}
func (m *AggregationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationRequest.Marshal(b, m, deterministic)
}
func (m *AggregationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationRequest.Merge(m, src)
}
func (m *AggregationRequest) XXX_Size() int {
	return xxx_messageInfo_AggregationRequest.Size(m)
}
func (m *AggregationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationRequest proto.InternalMessageInfo

func (m *AggregationRequest) GetSubTrees() [][]byte {
	if m != nil {
		return m.SubTrees
	}
	return nil
}

func (m *AggregationRequest) GetToken() int64 {
	if m != nil {
		return m.Token
	}
	return 0
}

type AggregationResult struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Token                int64    `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationResult) Reset()         { *m = AggregationResult{} }
func (m *AggregationResult) String() string { return proto.CompactTextString(m) }
func (*AggregationResult) ProtoMessage()    {}
func (*AggregationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *AggregationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationResult.Unmarshal(m, b)
}
func (m *AggregationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationResult.Marshal(b, m, deterministic)
}
func (m *AggregationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationResult.Merge(m, src)
}
func (m *AggregationResult) XXX_Size() int {
	return xxx_messageInfo_AggregationResult.Size(m)
}
func (m *AggregationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationResult.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationResult proto.InternalMessageInfo

func (m *AggregationResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AggregationResult) GetToken() int64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func init() {
	proto.RegisterType((*AggregationProposal)(nil), "boojum.protocol.leader_election.AggregationProposal")
	proto.RegisterType((*AggregationRequest)(nil), "boojum.protocol.leader_election.AggregationRequest")
	proto.RegisterType((*AggregationResult)(nil), "boojum.protocol.leader_election.AggregationResult")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0xcf, 0x4b, 0x85, 0x40,
	0x10, 0xc0, 0x71, 0x4c, 0xb2, 0x1c, 0x24, 0x68, 0x8b, 0x90, 0x08, 0x12, 0x4f, 0x9e, 0xbc, 0xf4,
	0x17, 0x78, 0xe9, 0x16, 0xc4, 0xd2, 0x3d, 0x56, 0x1d, 0x16, 0x6b, 0x75, 0x6c, 0x66, 0xf7, 0xff,
	0x0f, 0xd7, 0x7e, 0xbc, 0x07, 0xef, 0x36, 0x9f, 0x39, 0x7c, 0x99, 0x81, 0xab, 0x19, 0x45, 0x8c,
	0x45, 0x69, 0x57, 0x26, 0x4f, 0xea, 0xb1, 0x27, 0xfa, 0x08, 0xf3, 0xae, 0x81, 0x5c, 0xeb, 0xd0,
	0x8c, 0xc8, 0xef, 0xe8, 0x70, 0xf0, 0x13, 0x2d, 0xf5, 0x0b, 0xdc, 0x74, 0xd6, 0x32, 0x5a, 0xb3,
	0xf1, 0x95, 0x69, 0x25, 0x31, 0x4e, 0x95, 0x70, 0x61, 0xc6, 0x91, 0x51, 0xa4, 0x4c, 0xaa, 0xa4,
	0xc9, 0xf5, 0x2f, 0xd5, 0x03, 0xe4, 0x32, 0xd9, 0xc5, 0xf8, 0xc0, 0x58, 0x9e, 0x55, 0x49, 0x53,
	0xe8, 0xff, 0x45, 0xfd, 0x0c, 0xea, 0x20, 0xa7, 0xf1, 0x2b, 0xa0, 0x78, 0x75, 0x0f, 0x97, 0x12,
	0xfa, 0x37, 0x46, 0xdc, 0x72, 0x69, 0x53, 0xe8, 0x3f, 0xab, 0x5b, 0x38, 0xf7, 0xf4, 0x89, 0x4b,
	0x6c, 0xa5, 0x7a, 0x47, 0xdd, 0xc1, 0xf5, 0x51, 0x47, 0x82, 0xf3, 0xea, 0x0e, 0x32, 0x8e, 0x53,
	0xbc, 0xa9, 0xd0, 0x3f, 0x3a, 0x9d, 0xe8, 0xb3, 0xf8, 0xf3, 0xd3, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x07, 0x0e, 0x79, 0x18, 0x13, 0x01, 0x00, 0x00,
}
